'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {pathToFileURL}=require('node:url');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.stack));
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.waitForFunction(()=>window.demo?.tactical?.terrain);
 const ids=await page.evaluate(()=>{const t=demo.tactical,a=demo.elenco.controlado(),b=demo.elenco.criar('Oponente').id;demo.elenco.entrar(b,{x:demo.state.playerX+48});t.toggle.click();const c=t.combat;c.person(a).initiative=30;c.person(b).initiative=10;c.person(b).cell={x:c.person(a).cell.x+1,z:c.person(a).cell.z};t.operation('start');return {a,b};});
 const originalHp=await page.evaluate(id=>demo.tactical.healthOf(id).parts.get('torso').hp,ids.b);
 const first=await page.evaluate(({a,b})=>{const t=demo.tactical,c=t.combat;c.state.timer.enabled=true;c.state.timer.remaining=60;const ok=c.attack(a,'soco',b,'torso',{roll:20});c.state.paused=true;const d=t.dice.get(a).die;return {ok,shared:d instanceof FichaDado.Dado,result:d.rolagem.d20,busy:c.state.busy.remaining,duration:d.duracao};},ids);
 assert.equal(first.ok,true);assert.equal(first.shared,true);assert.equal(first.result,20);assert.ok(first.busy>first.duration,'temporizador espera a revelação');
 const hp=await page.evaluate(id=>demo.tactical.healthOf(id).parts.get('torso').hp,ids.b);assert.ok(hp<originalHp);
 const out=path.resolve(__dirname,'../pixel_art/generated/tatico');fs.mkdirSync(out,{recursive:true});
 await page.evaluate(id=>{const t=demo.tactical;t.dice.get(id).die.t=.35;t.animation.time=.3;},ids.a);await page.waitForTimeout(180);await page.locator('#scene').screenshot({path:path.join(out,'dado-rolando.png')});
 assert.equal(await page.evaluate(id=>demo.tactical.dice.get(id).die.t,ids.a),.35,'pausa congela o dado');
 await page.evaluate(id=>{const t=demo.tactical;t.dice.get(id).die.t=1.1;t.dice.get(id).die.passo(0);t.animation.time=1.1;},ids.a);await page.waitForTimeout(180);await page.locator('#scene').screenshot({path:path.join(out,'dado-resultado.png')});
 assert.equal(await page.evaluate(id=>demo.tactical.dice.get(id).die.estado().face,ids.a),20);
 assert.equal(await page.evaluate(id=>demo.tactical.healthOf(id).parts.get('torso').hp,ids.b),hp,'animação não repete dano');
 const beforePan=await page.evaluate(id=>demo.tactical.diceAnchor(id),ids.a);await page.evaluate(()=>demo.tactical.panCamera(55));const afterPan=await page.evaluate(id=>demo.tactical.diceAnchor(id),ids.a);assert.ok(afterPan.x<beforePan.x,'o dado segue a cabeça com a câmera livre');
 await page.evaluate(()=>demo.tactical.combat.undo());assert.equal(await page.evaluate(()=>demo.tactical.dice.size),0);
 assert.equal(await page.evaluate(id=>demo.tactical.healthOf(id).parts.get('torso').hp,ids.b),originalHp);
 const fortitude=await page.evaluate(({a,b})=>{const t=demo.tactical,c=t.combat;let rolls=0;c.random=()=>{rolls++;return 0;};c.state.paused=false;c.attack(a,'soco',b,'head',{roll:20});c.state.paused=true;return {rolls,attack:t.dice.get(a).die.rolagem.d20,save:t.dice.get(b).die.rolagem.d20,label:t.dice.get(b).label};},ids);
 assert.deepEqual(fortitude,{rolls:1,attack:20,save:1,label:'FORTITUDE'});
 await page.evaluate(id=>demo.elenco.registro(id).oculto=true,ids.b);assert.equal(await page.evaluate(id=>demo.tactical.diceAnchor(id),ids.b),null,'NPC oculto não revela dado');await page.evaluate(id=>demo.elenco.registro(id).oculto=false,ids.b);
 await page.evaluate(()=>{const t=demo.tactical;t.combat.undo();t.combat.state.paused=false;t.combat.attack(t.combat.current.id,'defender');});assert.equal(await page.evaluate(()=>demo.tactical.dice.size),0,'defender não faz teste');
 await page.waitForFunction(()=>!demo.tactical.combat.state.busy);
 const reaction=await page.evaluate(({a,b})=>{const t=demo.tactical,c=t.combat,p=c.person(a);c.move(a,{x:p.cell.x,z:p.cell.z+1});c.react(b,true);c.state.paused=true;return {reactor:c.state.busy.actor,die:t.dice.get(b).die.rolagem.d20,label:t.dice.get(b).label};},ids);
 assert.equal(reaction.reactor,ids.b);assert.equal(reaction.die,1);assert.equal(reaction.label,'OPORTUNIDADE');
 await page.evaluate(()=>demo.tactical.save());await page.waitForTimeout(650);await page.reload();await page.waitForFunction(()=>demo.tactical?.active);assert.equal(await page.evaluate(()=>demo.tactical.dice.size),0,'restaurar não reapresenta nem rerrola a ação');
 assert.deepEqual(errors,[]);console.log('PASS: dado da ficha nos ataques, Fortitude e oportunidades; resultado único, pausa, câmera, ocultos, desfazer e sessão.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
