'use strict';
const assert=require('node:assert/strict');
const {TacticalTerrain}=require('../mestre/tatico-terreno.js');
const {TacticalCombat,ACTIONS}=require('../mestre/tatico-regras.js');
const {CharacterHealth}=require('../health.js');
const room={x0:0,x1:960,focal:530,dWall:818,H:-99,eye:328,project(X,d,h,cc){const f=this.focal/d;return [240+(X-cc)*f,this.H+(this.eye-h)*f,f];}};
let count=0;
function test(name,fn){fn();count++;console.log('✓ '+name);}
function setup(n=2){const t=new TacticalTerrain(room),health=Array.from({length:n},()=>new CharacterHealth()),pos=Array.from({length:n},(_,i)=>({x:120+i*48,depth:554})),attrs=Array.from({length:n},()=>({mqn:1,sns:1,sbt:1}));let seconds=0;
  const c=new TacticalCombat({terrain:t,random:()=>.5,adapter:{attr:(id,a)=>attrs[id][a],training:()=>0,health:id=>health[id],position:id=>pos[id],player:id=>id==='0',move:(id,p)=>pos[id]={...p},injure:(id,r,ty,v)=>health[id].injure(r,ty,v),advance:dt=>seconds+=dt,hair:()=>true}});
  c.prepare('test',Array.from({length:n},(_,i)=>String(i)));c.state.participants.forEach((p,i)=>p.initiative=20-i);c.start();return {c,t,health,attrs,pos,get seconds(){return seconds;}};
}
function settle(c){for(let i=0;i<50&&c.state.busy;i++)c.tick(.1);}
test('grade: projeção, diagonal dupla, quina, terreno difícil e corpos',()=>{const t=new TacticalTerrain(room);const p=t.world({x:3,z:2}),s=t.project(p.x,p.depth,40);const q=t.unproject(s[0],s[1],40);assert.ok(Math.abs(p.x-q.x)<1e-8);assert.ok(Math.abs(p.depth-q.depth)<1e-8);assert.equal(t.cost({x:1,z:1},{x:2,z:2}),2);t.set({x:2,z:1},'bloqueado');assert.equal(t.cost({x:1,z:1},{x:2,z:2}),Infinity);t.set({x:2,z:1},'dificil');assert.equal(t.cost({x:1,z:1},{x:2,z:1}),2);assert.equal(t.path({x:1,z:1},{x:2,z:1},()=>({fallen:true})),null);});
test('fórmulas MQN/SENSO, iniciativa e fim de rodada único',()=>{const s=setup();assert.equal(s.c.current.ap,5);assert.equal(s.c.current.move,7);s.c.end();assert.equal(s.seconds,0);s.c.end();assert.equal(s.seconds,6);assert.equal(s.c.state.round,2);s.attrs[0].mqn=7;s.attrs[0].sns=7;s.c.begin();assert.equal(s.c.current.ap,11);assert.equal(s.c.current.move,13);s.attrs[0].mqn=0;s.attrs[0].sns=0;s.c.begin();assert.equal(s.c.current.ap,4);assert.equal(s.c.current.move,6);});
test('acerto, erro custam PA e repetição acompanha o golpe',()=>{const {c,health}=setup();const before=health[1].parts.get('torso').hp;assert.ok(c.attack('0','soco','1','torso',{roll:1}));assert.equal(health[1].parts.get('torso').hp,before);assert.equal(c.current.ap,3);settle(c);assert.equal(c.preview('0','soco','1','torso').repetition,2);assert.ok(c.attack('0','soco','1','torso',{roll:20}));assert.ok(health[1].parts.get('torso').hp<before);settle(c);assert.equal(c.attack('0','soco','1','torso'),false);});
test('cada golpe do catálogo tem execução válida e custa o valor definido',()=>{for(const [name,a] of Object.entries(ACTIONS)){const {c,t}=setup();const p=c.current;p.ap=20;p.conditions.fallen=name==='levantar';if(name==='limpar')p.conditions.eyes=1;t.set(p.cell,'terra');const region=a.regions?.[0]||'torso';assert.ok(c.attack('0',name,a.self?undefined:'1',region,{roll:15}),name);assert.equal(p.ap,20-a.cost,name);assert.ok(c.state.busy);settle(c);}});
test('membro ausente, apoio, cabelo e terra são requisitos reais',()=>{const {c,health}=setup();for(const s of ['near','far'])health[0].parts.get('hand_'+s).missing=true;assert.match(c.preview('0','soco','1').reason,/membros/);health[0].parts.get('thigh_near').fracture=true;assert.match(c.preview('0','chute','1').reason,/membros/);const b=setup();assert.match(b.c.preview('0','terra','1','eye_left').reason,/terra/);b.c.a.hair=()=>false;assert.match(b.c.preview('0','cabelo','1','head').reason,/cabelo/);});
test('oportunidade antes do passo, recusa mantém reação e aceite não custa PA',()=>{const {c}=setup();const before={...c.current.cell};assert.ok(c.move('0',{x:before.x,z:before.z+1}));assert.equal(c.state.pending.reaction,'1');assert.deepEqual(c.current.cell,before);const ap=c.person('1').ap;assert.ok(c.react('1',true));assert.equal(c.person('1').ap,ap);assert.equal(c.person('1').reaction,false);settle(c);assert.equal(c.current.cell.z,before.z+1);assert.equal(c.state.pending,null);const b=setup();b.c.move('0',{x:b.c.current.cell.x,z:1});b.c.react('1',false);settle(b.c);assert.equal(b.c.person('1').reaction,true);});
test('oportunidades múltiplas respeitam iniciativa e queda cancela trajeto',()=>{const {c}=setup(3);c.person('2').cell={x:2,z:1};assert.ok(c.move('0',{x:1,z:0}));assert.equal(c.state.pending.reaction,'1');c.react('1',false);assert.equal(c.state.pending.reaction,'2');c.current.conditions.fallen=true;c.react('2',false);assert.equal(c.state.pending,null);assert.equal(c.current.cell.x,2);});
test('empurrar não cria reação; desengajar permite sair',()=>{const {c}=setup();assert.ok(c.attack('0','empurrar','1','torso',{roll:20}));assert.equal(c.state.pending,null);assert.equal(c.person('1').reaction,true);const b=setup();b.c.attack('0','desengajar');settle(b.c);assert.ok(b.c.move('0',{x:2,z:1}));assert.equal(b.c.state.pending?.reaction,null);settle(b.c);});
test('comandos repetidos, atrasados e controlador incorreto não agem',()=>{const {c}=setup();const cmd={id:'abc',actor:'0',epoch:c.state.epoch,type:'attack',action:'soco',target:'1',region:'torso'};assert.ok(c.command(cmd,'player'));assert.equal(c.command(cmd,'player'),false);settle(c);assert.equal(c.current.ap,3);c.end();assert.equal(c.command({...cmd,id:'new'},'player'),false);assert.equal(c.command({id:'enemy',actor:'1',epoch:c.state.epoch,type:'end'},'player'),false);});
test('restauração pausa sem repetir dano; reação fica pendente',()=>{const {c}=setup();c.move('0',{x:2,z:1});const state=c.export();const b=setup();assert.ok(b.c.restore(state));assert.equal(b.c.state.paused,true);assert.equal(b.c.state.pending.reaction,'1');assert.equal(b.c.react('1',true),false);});
test('temporizador só consome decisão conectada de jogador',()=>{const {c}=setup();c.state.timer.enabled=true;c.state.timer.remaining=.2;c.tick(.1,{connected:false});assert.equal(c.state.timer.remaining,.2);c.state.paused=true;c.tick(.1);assert.equal(c.state.timer.remaining,.2);c.state.paused=false;c.tick(.1);c.tick(.1);assert.equal(c.current.id,'1');const time=c.state.timer.remaining;c.tick(.1);assert.equal(c.state.timer.remaining,time);});
test('efeitos temporários expiram no próximo turno; nocaute não mata',()=>{const {c,health,t}=setup();t.set(c.current.cell,'terra');c.attack('0','terra','1','eye_left',{roll:20});settle(c);assert.ok(c.person('1').conditions.eyes);assert.equal(health[1].vision.left,100);c.end();c.end();assert.equal(c.person('1').conditions.eyes,undefined);const b=setup();b.c.random=()=>0;b.c.attack('0','soco','1','head',{roll:20});settle(b.c);assert.ok(b.c.person('1').conditions.ko);assert.equal(b.health[1].dead,false);b.c.end();b.c.tick(.1);assert.equal(b.c.current.id,'0');assert.equal(b.c.person('1').conditions.ko,undefined);assert.ok(b.c.person('1').conditions.fallen);});
test('NPC oculto não aparece em estado nem log dos jogadores',()=>{const {c}=setup();c.a.hidden=id=>id==='1';c.log('segredo',['1']);const json=JSON.stringify(c.publicState());assert.ok(!json.includes('segredo'));assert.equal(c.publicState().participants.length,1);});
test('reordenar e retirar o ativo não repetem turnos nem avançam rodada cedo',()=>{const s=setup(3),c=s.c;c.end();assert.equal(c.current.id,'1');c.state.order=['1','0','2'];c.state.index=0;c.remove('1');assert.equal(c.current.id,'2');assert.equal(c.person('0').turns,1);assert.equal(s.seconds,0);c.end();assert.equal(s.seconds,6);assert.equal(c.current.id,'0');});
test('entrada tardia espera a próxima rodada e começa sem IA',()=>{const s=setup(3),c=s.c;c.remove('2');c.add('2');assert.equal(c.person('2').joined,2);assert.equal(c.person('2').ai,false);c.end();assert.equal(c.current.id,'1');c.end();assert.equal(c.state.round,2);assert.ok(c.state.order.includes('2'));assert.equal(c.person('2').turns,0);});
test('desfazer oportunidade restaura a decisão e a reação',()=>{const {c}=setup();c.move('0',{x:2,z:1});assert.equal(c.state.pending.reaction,'1');c.react('1',true);c.undo();assert.equal(c.person('1').reaction,true);assert.equal(c.state.pending.reaction,'1');assert.equal(c.state.paused,true);});
test('NPC oculto não vaza na fila de reações já consultadas',()=>{const {c}=setup(3);c.a.hidden=id=>id==='2';c.state.pending={actor:'0',reaction:'1',asked:['2'],path:[]};assert.deepEqual(c.publicState().pending.asked,[]);});
test('cada pessoa usa seu SENSO e MÁQUINA sem consumir recursos das demais',()=>{const {c,attrs}=setup(3);Object.assign(attrs[0],{sns:0,mqn:1});Object.assign(attrs[1],{sns:7,mqn:7});Object.assign(attrs[2],{sns:3,mqn:0});c.finish();c.prepare('test',['0','1','2']);c.state.participants.forEach((p,i)=>p.initiative=20-i);c.start();
  assert.deepEqual(c.state.participants.map(p=>[p.ap,p.apMax,p.move,p.moveMax]),[[4,4,7,7],[11,11,13,13],[7,7,6,6]]);
  const untouched=JSON.stringify(c.state.participants.slice(1));c.attack('0','soco','1','torso',{roll:1});settle(c);assert.equal(c.person('0').ap,2);assert.equal(JSON.stringify(c.state.participants.slice(1)),untouched);
  c.end();assert.equal(c.current.id,'1');assert.equal(c.current.ap,11);c.attack('1','soco','0','torso',{roll:1});settle(c);assert.equal(c.person('1').ap,9);assert.equal(c.person('0').ap,0);assert.equal(c.person('2').ap,7);assert.equal(c.person('2').move,6);
  const saved=c.export();c.restore(saved);assert.deepEqual(c.state.participants.map(p=>[p.ap,p.apMax,p.move,p.moveMax]),saved.participants.map(p=>[p.ap,p.apMax,p.move,p.moveMax]));c.state.paused=false;c.end();assert.equal(c.current.ap,7);c.end();assert.equal(c.current.ap,4);assert.equal(c.person('1').ap,0);
});
test('alcance distingue o próprio ator, distância e quina realmente bloqueada',()=>{const {c,t}=setup();const a=c.person('0'),b=c.person('1');assert.match(c.preview('0','soco','0').reason,/quem está agindo/);b.cell={x:a.cell.x+2,z:a.cell.z};assert.match(c.preview('0','soco','1').reason,/Fora de alcance/);
  b.cell={x:a.cell.x+1,z:a.cell.z+1};assert.equal(c.preview('0','soco','1').reason,'');t.set({x:a.cell.x+1,z:a.cell.z},'bloqueado');assert.match(c.preview('0','soco','1').reason,/quina/);t.set({x:a.cell.x+1,z:a.cell.z},'livre');assert.equal(c.preview('0','soco','1').reason,'');
  for(let z=-1;z<=1;z++)for(let x=-1;x<=1;x++){if(!x&&!z)continue;a.cell={x:3,z:2};b.cell={x:3+x,z:2+z};assert.equal(c.preview('0','soco','1').reason,'',`contato ${x},${z}`);assert.equal(t.adjacent(a.cell,b.cell),t.adjacent(b.cell,a.cell),`contato simétrico ${x},${z}`);}
});
console.log(`${count} cenários táticos aprovados.`);
