/* HUD tático desenhado no próprio render, em uma grade de pixels 480x270. */
(function(root){
'use strict';
const C={black:'#080b16',dark:'#141626',panel:'#242237',shade:'#373047',edge:'#665067',light:'#a2787b',ink:'#f4dfb6',dim:'#b2a0b4',gold:'#eebc73',copper:'#9c674e',green:'#93cba7',red:'#ea8c8d'};
class TacticalHUD{
 constructor(canvas,onIntent){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onIntent=onIntent;this.hits=[];this.images=new Map();this.icons=new Map();this.menu=false;this.page=0;this.hover=null;}
 text(t,x,y,color=C.ink,font='3x5',align='left'){root.PixelKit.drawText(this.ctx,String(t),Math.round(x),Math.round(y),{color,font,align,shadow:{color:C.black,dx:1,dy:1}});}
 rect(x,y,w,h,color){this.ctx.fillStyle=color;this.ctx.fillRect(Math.round(x),Math.round(y),w,h);}
 panel(x,y,w,h,accent=C.edge){this.rect(x+2,y+2,w,h,C.black);this.rect(x+2,y,w-4,h,C.black);this.rect(x,y+2,w,h-4,C.black);this.rect(x+2,y+1,w-4,h-2,accent);this.rect(x+1,y+2,w-2,h-4,accent);this.rect(x+3,y+3,w-6,h-6,C.dark);this.rect(x+3,y+3,w-6,1,C.light);this.rect(x+4,y+5,w-8,h-10,C.panel);this.rect(x+4,y+h-5,w-8,1,C.shade);for(const xx of [x+2,x+w-4])for(const yy of [y+2,y+h-4]){this.rect(xx,yy,2,2,C.copper);this.rect(xx,yy,1,1,C.gold);}}
 hitAt(x,y){return [...this.hits].reverse().find(h=>x>=h.x&&y>=h.y&&x<h.x+h.w&&y<h.y+h.h&&(!h.contains||h.contains(x,y)));}
 pointer(x,y){this.hover=this.hitAt(x,y)||null;return !!this.hover;}
 click(x,y){const h=this.hitAt(x,y);if(!h)return false;if(h.disabled||!h.intent)return true;const i=h.intent;if(i.type==='menu'){this.menu=!this.menu;return true;}if(i.type==='page'){this.page+=i.delta;return true;}if(i.type==='itemPage'){this.itemPage=(this.itemPage||0)+i.delta;return true;}if(i.type==='master')this.menu=false;this.onIntent(i);return true;}
 block(x,y,w,h){this.hits.push({x,y,w,h});}
 button(x,y,w,h,label,intent,{selected=false,disabled=false,tip=null}={}){const hot=this.hover?.intent&&JSON.stringify(this.hover.intent)===JSON.stringify(intent),edge=selected?C.gold:hot?C.light:C.edge;this.rect(x,y,w,h,C.black);this.rect(x+1,y+1,w-2,h-2,edge);this.rect(x+2,y+2,w-4,h-4,selected?'#574039':C.panel);this.rect(x+2,y+h-3,w-4,1,C.dark);if(label)this.text(label,x+w/2,y+(h-5)/2,disabled?'#756677':selected?C.gold:C.ink,'3x5','center');this.hits.push({x,y,w,h,intent,disabled,tip});}
 portrait(url,x,y,w,h){if(!url)return;let im=this.images.get(url);if(!im){im=new Image();im.src=url;this.images.set(url,im);}if(im.complete&&im.naturalWidth)this.ctx.drawImage(im,x,y,w,h);}
 icon(id,x,y,size=16){this.ctx.imageSmoothingEnabled=false;this.ctx.drawImage(root.TacticalIcons.get(id),x,y,size,size);}
 anatomy(view,target){const s=view.selection,x=298,y=40;this.panel(x,y,180,167,C.copper);this.block(x,y,180,167);this.text('MIRA ANATÔMICA',x+9,y+9,C.gold,'5x7');this.button(x+163,y+7,10,11,'X',{type:'select',anatomy:false});this.text((target?.name||'ESCOLHA UM ALVO').slice(0,34),x+9,y+22,C.dim);
 const map=root.HEALTH_ANATOMY,ox=x+10,oy=y+29;this.anatomyCache||=new Map();
 for(const [id,shape] of Object.entries(map.shapes)){let mask=this.anatomyCache.get(id);if(!mask){const c=document.createElement('canvas');c.width=map.width;c.height=map.height;const g=c.getContext('2d'),path=new Path2D(shape);g.fill(path);const data=g.getImageData(0,0,c.width,c.height).data,pixels=[];for(let yy=0;yy<c.height;yy++)for(let xx=0;xx<c.width;xx++)if(data[(yy*c.width+xx)*4+3])pixels.push([xx,yy]);const xs=pixels.map(p=>p[0]),ys=pixels.map(p=>p[1]);mask={pixels,path,x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs)+1,h:Math.max(...ys)-Math.min(...ys)+1};this.anatomyCache.set(id,mask);}
 const part=target?.anatomy?.[id],allowed=view.regions?.includes(id)&&!part?.missing,selected=s.region===id;
 for(const [px,py] of mask.pixels)this.rect(ox+px,oy+py,1,1,selected?C.copper:part?.missing?C.black:part?.hp<part?.maxHp?C.red:allowed?'#70616d':C.shade);
 this.ctx.save();this.ctx.translate(ox,oy);this.ctx.fillStyle=selected?C.gold:'#b2a0a0';if(map.bones[id]&&!part?.missing)this.ctx.fill(new Path2D(map.bones[id]),'evenodd');this.ctx.restore();
 this.hits.push({x:ox+mask.x,y:oy+mask.y,w:mask.w,h:mask.h,intent:{type:'select',region:id},disabled:!allowed,tip:root.HEALTH_PARTS[id],contains:(px,py)=>this.ctx.isPointInPath(mask.path,px-ox,py-oy)});
 }
 const tx=x+83,v=view.preview;this.text((root.HEALTH_PARTS[s.region]||'').slice(0,23),tx,y+36,C.gold);this.text(v?`CD ${v.cd} · ${v.chance}%`:'ESCOLHA O ALVO',tx,y+47,C.ink,'5x7');
 const labels={base:'BASE',machine:'MQN',substance:'SBT',attackTraining:'LUTA',defenseTraining:'REFLEXOS',region:'REGIÃO',repetition:'REPETIÇÃO',defend:'DEFENDENDO',fallen:'CAÍDO',eyes:'OLHOS SUJOS'};
 Object.entries(v?.factors||{}).forEach(([key,value],i)=>this.text(`${labels[key]} ${value>0?'+':''}${value}`,tx,y+62+i*8,C.dim));
 this.button(tx,y+146,40,12,'OLHO E',{type:'select',region:'eye_left'},{disabled:!view.regions?.includes('eye_left')||target?.anatomy?.eye_left?.missing});this.button(tx+43,y+146,40,12,'OLHO D',{type:'select',region:'eye_right'},{disabled:!view.regions?.includes('eye_right')||target?.anatomy?.eye_right?.missing});
 }
 draw(view,ctx=this.ctx){this.ctx=ctx;this.view=view;this.hits=[];if(!view?.state||view.state.phase==='off')return;const g=ctx;g.save();g.imageSmoothingEnabled=false;const s=view.state,sel=view.selection||{},p=s.participants.find(q=>q.id===s.current),target=s.participants.find(q=>q.id===sel.target),master=view.role==='master';
 this.panel(2,1,476,35);this.block(0,0,480,37);this.text(s.phase==='preparation'?'PREPARO':s.paused?'PAUSADO':'RODADA',9,7,C.dim);this.text(s.round||'—',25,17,C.gold,'5x7','center');if(s.timer.enabled)this.text(`${Math.ceil(s.timer.remaining)}s`,25,27,C.green,'3x5','center');
 const order=s.order.length?s.order:s.participants.map(q=>q.id),base=Math.max(0,order.indexOf(p?.id)-2),start=Math.max(0,Math.min(Math.max(0,order.length-7),base+this.page*7));
 order.slice(start,start+7).forEach((id,i)=>{const q=s.participants.find(q=>q.id===id);if(!q)return;const x=51+i*44;this.button(x,5,42,26,'',{type:'select',target:id},{selected:sel.target===id,tip:`${q.name} · PA ${q.ap}/${q.apMax} · MOV ${q.move}`});this.portrait(q.portrait,x+2,8,12,17);this.text(q.name.slice(0,6),x+15,9,C.ink);this.text(`PA ${q.ap}`,x+15,18,C.green);if(id===p?.id){this.rect(x+1,5,40,2,C.gold);this.rect(x+18,30,6,2,C.gold);}this.rect(x+2,27,3,2,q.team==='hostil'?C.red:q.team==='aliado'?C.green:C.dim);if(q.conditions.ko||q.conditions.fallen)this.text(q.conditions.ko?'Z':'v',x+34,24,C.red);});
 this.button(361,5,11,12,'<',{type:'page',delta:-1});this.button(361,19,11,12,'>',{type:'page',delta:1});this.button(376,5,46,26,view.cameraMode==='free'?'FOCAR [C]':'CÂMERA [C]',{type:'camera',mode:'follow'});this.button(426,5,47,26,master?'MESTRE':s.timer.enabled?`${Math.ceil(s.timer.remaining)}s`:'LOCAL',master?{type:'menu'}:null,{disabled:!master});
 this.panel(1,209,478,60,C.copper);this.block(0,208,480,62);this.rect(5,212,470,1,C.gold);
 this.portrait(p?.portrait,7,217,22,29);this.text((p?.name||'AGUARDANDO').slice(0,19),33,217,C.ink);this.text(`PA ${p?.ap??0}/${p?.apMax??0}`,33,227,C.gold);
 for(let i=0;i<Math.min(11,p?.apMax||0);i++){this.rect(33+i*6,236,5,5,C.black);this.rect(34+i*6,237,3,3,i<(p?.ap||0)?C.gold:C.shade);if(i<(p?.ap||0))this.rect(34+i*6,237,3,1,C.ink);}
 this.text(`MOV ${p?.move??0}/${p?.moveMax??0}`,8,249,C.green);this.text(`REAÇÃO ${p?.reaction?'1':'0'}`,8,258,p?.reaction?C.dim:C.edge);
 this.button(64,250,48,15,'BOLSA [I]',master?{type:'inventory'}:{type:'select',inventory:!sel.inventory},{tip:'Bolsa do selecionado ou do personagem do turno'});
 Object.entries(root.TACTICAL_ACTIONS).filter(([,a])=>!a.self).forEach(([id,a],i)=>{const x=117+i*25;this.button(x,217,24,26,'',{type:'select',action:id},{selected:sel.action===id,tip:`${a.name} · ${a.cost} PA${p?.uses[id]?` · +${p.uses[id]*2} CD`:''}`});this.icon(id,x+3,220);this.rect(x+16,233,7,8,C.black);this.text(a.cost,x+19,235,C.gold,'3x5','center');});
 Object.entries(root.TACTICAL_ACTIONS).filter(([,a])=>a.self).forEach(([id,a],i)=>this.button(117+i*62,248,60,15,`${a.name} 2`,{type:'self',action:id},{disabled:!view.canAct,tip:a.name}));
 this.button(371,217,103,13,`MIRA: ${(root.TACTICAL_REGIONS[sel.region]||'TÓRAX').toUpperCase()}`,{type:'select',anatomy:!sel.anatomy},{selected:!!sel.anatomy});
 const prep=s.phase==='preparation';this.button(371,232,103,16,prep?'INICIAR BATALHA':view.preview?.reason?'VER IMPEDIMENTO':view.preview?`ATACAR · ${view.preview.chance}%`:'ESCOLHA O ALVO',prep?{type:'master',op:'start'}:{type:'confirm'},{selected:!!view.canAct&&!view.preview?.reason,disabled:prep?!master:!view.canAct||!!view.preview?.reason||!view.preview,tip:view.preview?.reason||view.preview?.effect});
 this.button(371,251,103,14,'ENCERRAR TURNO',{type:'end'},{disabled:!view.canAct});
 if(target){const text=`ALVO: ${target.name.slice(0,17)} · PA ${target.ap}/${target.apMax} · ${root.TACTICAL_ACTIONS[sel.action]?.name||''}`;this.rect(116,198,Math.min(350,text.length*4+8),10,C.dark);this.text(text,120,200,C.dim);}
 const last=s.log?.at(-1);if(last&&!sel.anatomy){this.rect(7,188,Math.min(465,last.text.length*4+8),9,'#141626e8');this.text(last.text.slice(0,112),11,190,C.dim);}
 if(view.notice){this.panel(7,40,310,25,C.edge);this.block(7,40,310,25);const words=view.notice.split(' '),lines=[''];for(const word of words){let n=lines.length-1;if(lines[n].length+word.length>73&&lines[n]){lines.push('');n++;}lines[n]+=(lines[n]?' ':'')+word;}lines.slice(0,2).forEach((line,i)=>this.text(line,14,47+i*8,C.ink));}
 if(sel.anatomy)this.anatomy(view,target);
 if(view.inventory){const bag=view.inventory;this.panel(7,42,280,160,C.copper);this.block(7,42,280,160);this.text(`BOLSA: ${bag.name}`.slice(0,48),15,51,C.gold);this.button(269,49,11,12,'X',{type:'select',inventory:false});this.button(15,65,95,13,'USAR EM MIM',{type:'select',target:bag.owner});this.text('ALVO: '+(target?.name||bag.name).slice(0,30),117,69,C.dim);this.itemPage=Math.max(0,Math.min(this.itemPage||0,Math.max(0,Math.ceil(bag.entries.length/5)-1)));bag.entries.slice(this.itemPage*5,this.itemPage*5+5).forEach((e,i)=>this.button(15,83+i*20,260,18,`${e.qty}x ${e.label} · ${e.preview.cost??'?'} PA`,{type:'item',entry:e.id,target:bag.target,region:sel.region},{disabled:!view.canAct||!!e.preview.reason,tip:e.preview.reason||'Usar item'}));this.button(15,185,36,12,'<',{type:'itemPage',delta:-1});this.button(239,185,36,12,'>',{type:'itemPage',delta:1});}
 if(this.hover?.tip){const text=this.hover.tip,xx=Math.max(6,Math.min(260,this.hover.x)),action=this.hover.intent?.action,yy=action?125:this.hover.y>200?171:42;this.panel(xx,yy,action?208:Math.min(214,text.length*4+14),action?78:22,C.light);if(action){this.icon(action,xx+5,yy+7,64);this.text(text.slice(0,32),xx+72,yy+20,C.ink);this.text('64 × 64',xx+72,yy+32,C.dim);}else this.text(text.slice(0,50),xx+7,yy+8,C.ink);}
 if(this.editOrder&&master){this.panel(7,40,278,46,C.gold);this.block(7,40,278,46);this.text('ARRASTE OS RETRATOS PARA REORDENAR',14,48,C.gold);[['AGORA','activate'],['REMOVER','remove'],['INCLUIR','add'],['FECHAR','order']].forEach(([label,op],i)=>this.button(13+i*67,61,64,17,label,{type:'master',op},{disabled:['activate','remove'].includes(op)&&!target}));}
 if(s.pending?.reaction){this.hits=this.hits.filter(h=>h.y<37);this.block(0,37,480,233);this.panel(92,82,296,103,C.gold);const q=s.participants.find(q=>q.id===s.pending.reaction);this.text('ATAQUE DE OPORTUNIDADE',240,94,C.gold,'5x7','center');this.portrait(q?.portrait,107,116,22,28);this.text((q?.name||'AGUARDE O MESTRE').slice(0,35),139,117,C.ink);this.text('O movimento aguarda esta reação.',139,130,C.dim);this.button(104,151,132,22,'ATACAR · 1 REAÇÃO',{type:'reaction',accept:true},{disabled:!view.canReact,selected:true});this.button(244,151,132,22,'DEIXAR PASSAR',{type:'reaction',accept:false},{disabled:!view.canReact});}
 if(this.menu&&master){this.panel(240,41,237,86,C.copper);this.block(240,41,237,86);const entries=[['INICIAR','start'],[s.paused?'RETOMAR':'PAUSAR','pause'],['PULAR TURNO','skip'],['DESFAZER','undo'],['AJUSTAR MESA','settings'],['ENCERRAR LUTA','finish'],['EDITAR INICIATIVA','order'],['INCLUIR PESSOAS','add']];entries.forEach(([label,op],i)=>this.button(246+(i%2)*113,48+Math.floor(i/2)*18,109,15,label,{type:'master',op},{disabled:op==='start'?!prep:op==='pause'||op==='skip'?prep:false}));}
 for(const roll of view.dice||[]){this.rollRenderer||=new root.FichaDado.Dado();Object.assign(this.rollRenderer,roll.state);this.rollRenderer.desenhar(g,roll.anchor.x,roll.anchor.y,{escala:1,compacto:true});this.text(roll.label.toUpperCase(),roll.anchor.x+19,roll.anchor.y+8,C.gold);}
 g.restore();
 }
}
root.TacticalHUD=TacticalHUD;
})(typeof window!=='undefined'?window:globalThis);

